### ISSUE TITLE
sub package존재할 경우 컴파일 에러 발생

### ISSUE THREAD

**Issue by HGUISEL** [HGUISEL/JChecker-Engine#4]

**Comment by Yessir-kim** [comment]
This issue not a bug. We cover all sub packages when compile project. I think it's a problem that has been caused by overlapping with the edu.zip file issue.

**Comment by Yessir-kim** [comment]
This issue not a bug. We cover all sub packages when compile project. I think it's a problem that has been caused by overlapping with the edu.zip file issue.
